version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile      # Production Dockerfile
    container_name: recruitment-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: recruitment-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: recruitment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recruitment_manager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
