name: CD Deployment

on:
  push:
    branches: [ main ]  # Trigger deployment when main branch is updated
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to On-Prem Server
        run: |
          cd ~/GWUIM-recruitment/deployment
          docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/recruitment-backend:latest
          docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/recruitment-frontend:latest
          docker compose -f docker-compose.dev.yml down
          docker compose -f docker-compose.dev.yml up -d

